name: BDD Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries for PostgreSQL
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run the server locally
        run: |
          echo "\n*** STARTING APPLICATION ***\n"
          honcho start
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/testdb"

      - name: Run unit tests with behave
        run: behave
  
